# Generated by Django 4.2 on 2023-05-02 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juniordeveloper',
            name='seniorDeveloper',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='seniorManager',
        ),
        migrations.RemoveField(
            model_name='seniordeveloper',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='seniormanager',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='seniorManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.seniormanager'),
        ),
        migrations.AddField(
            model_name='manager',
            name='seniorDeveloper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.seniordeveloper'),
        ),
        migrations.AddField(
            model_name='seniordeveloper',
            name='juniorDeveloper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.juniordeveloper'),
        ),
        migrations.AddField(
            model_name='seniormanager',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.manager'),
        ),
    ]
