# Generated by Django 4.2 on 2023-05-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
